name: PHP Composer

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP with composer v2
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
      env:
        DELIRABBIT_CLIENT_ID: ${{ secrets.DELIRABBIT_CLIENT_ID }}
        DELIRABBIT_ENV: beta
        DELIRABBIT_PASSWORD: ${{ secrets.DELIRABBIT_PASSWORD }}
        DELIRABBIT_USERNAME: ${{ vars.DELIRABBIT_USERNAME }}
        
